using System;
using System.Collections.Generic;
using Mirror;
using UnityEngine;
using JustAGame.Inventory;
using JustAGame.Core.Network;

namespace JustAGame.VendingMachine
{
    /// <summary>
    /// Host/Server-authoritative Vending Machine.
    /// Evaluates purchase requests from clients, validates item validity, catalog prices, 
    /// player proximity, and cooldowns on the server side.
    /// Supports dynamic host-only item creation with auto-incrementing IDs.
    /// Distributes items according to the Odd/Even rule:
    /// - Odd Item ID  -> Assigned to the buyer's inventory.
    /// - Even Item ID -> Assigned to the host's inventory.
    /// </summary>
    public class VendingMachine : NetworkBehaviour
    {
        [Header("Catalog Reference (Optional)")]
        [Tooltip("Optional static catalog of purchasable items and their server-controlled prices.")]
        [SerializeField] private ItemCatalog catalog;

        [Header("Dynamic Item Creation (Host Authoritative)")]
        [Tooltip("Initial number of items automatically generated by the Host upon server start.")]
        [SerializeField] private int initialHostItemCount = 4;

        [Tooltip("Base price for host-generated items.")]
        [SerializeField] private int baseItemPrice = 15;

        [Header("Validation & Security")]
        [Tooltip("Maximum allowed distance between player and vending machine to allow interaction.")]
        [SerializeField] private float maxInteractionDistance = 5.0f;

        [Tooltip("Cooldown period in seconds between purchase requests to prevent RPC spamming.")]
        [SerializeField] private float purchaseCooldownSeconds = 0.5f;

        // Auto-incrementing item ID counter (server-only)
        [SyncVar] private int _nextAutoIncrementId = 1;

        // Synchronized list of available items created by the host
        private readonly SyncList<VendingItemEntry> _availableItems = new SyncList<VendingItemEntry>();

        // Server-side cooldown tracking: connectionId -> lastPurchaseTime
        private readonly Dictionary<int, float> _cooldownTracker = new Dictionary<int, float>();

        // Client-side events for UI feedback and dynamic button updates
        public static event Action<int, string> OnLocalPurchaseSuccess;
        public static event Action<string> OnLocalPurchaseFailed;
        public event Action<IReadOnlyList<VendingItemEntry>> OnAvailableItemsUpdated;

        public ItemCatalog Catalog => catalog;
        public IReadOnlyList<VendingItemEntry> AvailableItems => _availableItems;

        public override void OnStartServer()
        {
            base.OnStartServer();

            // Host authoritatively creates the initial items with incrementing IDs (1, 2, 3, 4...)
            for (int i = 0; i < initialHostItemCount; i++)
            {
                ServerCreateNewItem($"Item #{_nextAutoIncrementId}", baseItemPrice + (i * 5));
            }
        }

        public override void OnStartClient()
        {
            base.OnStartClient();
            _availableItems.Callback += HandleAvailableItemsChanged;

            // Trigger initial state
            OnAvailableItemsUpdated?.Invoke(_availableItems);
        }

        public override void OnStopClient()
        {
            _availableItems.Callback -= HandleAvailableItemsChanged;
            base.OnStopClient();
        }

        private void OnDestroy()
        {
            _availableItems.Callback -= HandleAvailableItemsChanged;
        }

        private void HandleAvailableItemsChanged(SyncList<VendingItemEntry>.Operation op, int itemIndex, VendingItemEntry oldItem, VendingItemEntry newItem)
        {
            OnAvailableItemsUpdated?.Invoke(_availableItems);
        }

        #region Host Authoritative Item Creation

        /// <summary>
        /// Creates a new purchasable item in the vending machine. Strictly server/host-authoritative.
        /// Incrementing IDs (1, 2, 3...) are assigned sequentially.
        /// </summary>
        [Server]
        public void ServerCreateNewItem(string itemName = null, int price = 15)
        {
            int assignedId = _nextAutoIncrementId++;
            string finalName = string.IsNullOrEmpty(itemName) ? $"Item #{assignedId}" : itemName;
            var entry = new VendingItemEntry(assignedId, finalName, price);

            _availableItems.Add(entry);
            Debug.Log($"[VendingMachine Server] Host created new item {entry.name} with ID {assignedId} at price ${price}");
        }

        /// <summary>
        /// Command allowing the Host client to trigger dynamic item creation at runtime.
        /// Rejects requests from non-host clients!
        /// </summary>
        [Command(requiresAuthority = false)]
        public void CmdHostCreateItem(string itemName, int price, NetworkConnectionToClient sender = null)
        {
            // Security: Verify that the sender is the local host connection!
            if (sender != NetworkServer.localConnection)
            {
                Debug.LogWarning("[VendingMachine] Unauthorized client attempted to create items. Action blocked.");
                TargetRpcPurchaseFailed(sender, "Only the Host is authorized to create items.");
                return;
            }

            ServerCreateNewItem(itemName, price);
        }

        #endregion

        #region Client Commands

        /// <summary>
        /// Request to purchase an item. The client ONLY passes the itemId.
        /// The server determines the price, unique identifier, and authorization rules.
        /// </summary>
        [Command(requiresAuthority = false)]
        public void CmdRequestPurchase(int itemId, NetworkConnectionToClient sender = null)
        {
            if (sender == null || sender.identity == null)
            {
                Debug.LogWarning("[VendingMachine] Purchase rejected: Invalid sender connection.");
                return;
            }

            int connectionId = sender.connectionId;
            float currentTime = Time.time;

            // 1. Anti-spam / Cooldown Check
            if (_cooldownTracker.TryGetValue(connectionId, out float lastTime))
            {
                if (currentTime - lastTime < purchaseCooldownSeconds)
                {
                    TargetRpcPurchaseFailed(sender, "Please wait a moment before purchasing again.");
                    return;
                }
            }
            _cooldownTracker[connectionId] = currentTime;

            // 2. Proximity Check (Zero-Trust Anti-Teleport)
            GameObject playerObj = sender.identity.gameObject;
            float distance = Vector3.Distance(playerObj.transform.position, transform.position);
            if (distance > maxInteractionDistance)
            {
                TargetRpcPurchaseFailed(sender, "You are too far from the vending machine.");
                return;
            }

            // 3. Resolve Item Details and Authoritative Price
            int itemPrice = -1;
            string itemName = $"Item {itemId}";

            // First check host-created dynamic items
            bool foundInDynamicList = false;
            for (int i = 0; i < _availableItems.Count; i++)
            {
                if (_availableItems[i].id == itemId)
                {
                    itemPrice = _availableItems[i].price;
                    itemName = _availableItems[i].name;
                    foundInDynamicList = true;
                    break;
                }
            }

            // Fallback to static catalog if not found in dynamic items
            if (!foundInDynamicList && catalog != null && catalog.TryGetItem(itemId, out ItemDefinition itemDef))
            {
                itemPrice = itemDef.Price;
                itemName = itemDef.ItemName;
            }

            if (itemPrice < 0)
            {
                TargetRpcPurchaseFailed(sender, $"Item ID {itemId} is not available in the vending machine.");
                return;
            }

            // 4. Buyer Inventory & Balance Check
            var buyerInventory = playerObj.GetComponent<PlayerInventory>();
            if (buyerInventory == null)
            {
                TargetRpcPurchaseFailed(sender, "Buyer has no valid inventory component.");
                return;
            }

            if (!buyerInventory.HasEnoughMoney(itemPrice))
            {
                TargetRpcPurchaseFailed(sender, $"Insufficient funds. Item costs ${itemPrice}, but you have ${buyerInventory.Money}.");
                return;
            }

            // 5. Deduct Currency Authoritatively on Server
            if (!buyerInventory.ServerDeductMoney(itemPrice))
            {
                TargetRpcPurchaseFailed(sender, "Transaction failed while deducting funds.");
                return;
            }

            // 6. Generate Server Unique Identifier (GUID)
            string uniqueId = Guid.NewGuid().ToString("N");
            ItemData purchasedItem = new ItemData(itemId, uniqueId);

            // 7. Odd / Even Allocation Rule
            bool isOdd = (itemId % 2 != 0);

            if (isOdd)
            {
                // Odd Item ID: Add to the buyer's inventory
                buyerInventory.ServerAddItem(purchasedItem);
                TargetRpcPurchaseSuccess(sender, itemId, $"Purchased Item {itemId} ({itemName})! Added to YOUR inventory (Odd ID).");
                Debug.Log($"[VendingMachine] Item {itemId} (ODD) assigned to Buyer (Conn {connectionId}).");
            }
            else
            {
                // Even Item ID: Add to the HOST's player inventory
                PlayerInventory hostInventory = GameNetworkManager.GetHostInventory();

                if (hostInventory != null)
                {
                    hostInventory.ServerAddItem(purchasedItem);
                    TargetRpcPurchaseSuccess(sender, itemId, $"Purchased Item {itemId} ({itemName})! Added to HOST's inventory (Even ID).");
                    Debug.Log($"[VendingMachine] Item {itemId} (EVEN) assigned to Host's inventory.");
                }
                else
                {
                    // Fallback in case host character is not found
                    buyerInventory.ServerAddItem(purchasedItem);
                    TargetRpcPurchaseSuccess(sender, itemId, $"Purchased Item {itemId}! Host not found, redirected to your inventory.");
                    Debug.LogWarning("[VendingMachine] Host player inventory not found! Fallback to buyer.");
                }
            }
        }

        #endregion

        #region Target RPC Responses

        [TargetRpc]
        private void TargetRpcPurchaseSuccess(NetworkConnection target, int itemId, string message)
        {
            Debug.Log($"[VendingMachine Client] Success: {message}");
            OnLocalPurchaseSuccess?.Invoke(itemId, message);
        }

        [TargetRpc]
        private void TargetRpcPurchaseFailed(NetworkConnection target, string reason)
        {
            Debug.LogWarning($"[VendingMachine Client] Purchase Failed: {reason}");
            OnLocalPurchaseFailed?.Invoke(reason);
        }

        #endregion
    }
}
